import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 100,
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  initialsCircle: {
    backgroundColor: '#97D0FEFF',
    borderRadius: 20,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#246396',
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#246396',
    fontWeight: 'bold',
  },
  userLabel: {
    fontSize: 14,
    color: '#246396',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },
  introWrap: {
    alignItems: 'center',
    marginTop: 8,
  },
  introLineSmall: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 22,
    color: '#246396',
    textAlign: 'center',
    lineHeight: 30,
  },
  introLineBig: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 32,
    color: '#246396',
    textAlign: 'center',
    marginTop: 8,
  },
  contentArea: {
    flex: 1,
    justifyContent: 'flex-end',   
    paddingBottom: 200,           
  },
  cardBox: {
    backgroundColor: '#FFF176',
    borderRadius: 28,
    paddingVertical: 22,
    paddingHorizontal: 24,
    minHeight: 260,               
    justifyContent: 'flex-start',
    shadowColor: '#313131FF',
    shadowOpacity: 0.8,
    shadowOffset: { width: 4, height: 6 },
    shadowRadius: 8,
  },
  templateRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    rowGap: 8,
    columnGap: 8,
  },
  templateText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 30,
    color: '#2C6F33',
    lineHeight: 42,
  },
  blankInput: {
    height: 56,
    minWidth: '78%',
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: '#F9DAFAA8',
    borderWidth: 2,
    borderColor: '#F9DAFAFF',
    fontFamily: 'ArchitectsDaughter',
    fontSize: 28,
    color: '#2C6F33',
    textAlign: 'center',
  },
  blankInputFocused: {
    borderColor: '#FFFFFF',
    borderWidth: 2,
    shadowColor: '#FFFFFF',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 9,
  },
  blankInputDisabled: {
    backgroundColor: '#E6E6E6',
    borderColor: '#BDBDBD',
  },
  blankInputCorrect: {
    backgroundColor: '#CBF6B6BD',
    borderColor: '#CBF6B6FF',
  },
  blankInputWrong: {
    backgroundColor: '#F86A6ACD',
    borderColor: '#F86A6AFF',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#313131FF',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navIconActive: {
    shadowColor: '#FFFFFF',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 4,
  },
  navText: {
    fontSize: 14,
    color: '#97D0FEFF',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
    textAlign: 'center',
    width: '100%',
  },
  hintText: {
    marginTop: 3,
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#246396',
    marginLeft: 9,
  },
});

export default styles;
