import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  initialsCircle: {
    backgroundColor: '#8feda0ff',
    borderColor: '#2c6f33',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1.5,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter-Regular',
    color: '#2c6f33',
    fontWeight: 'bold',
    fontSize: 18,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#fff176',
    borderColor: '#4CAF50',
    borderWidth: 2,
    borderRadius: 16,
    width: 370,
    height: 300,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    position: 'relative',
  },
  word: {
    fontSize: 50,
    fontFamily: 'ArchitectsDaughter-Regular',
    fontWeight: 'bold',
    color: '#2c6f33',
  },
  definition: {
    fontSize: 30,
    fontFamily: 'ArchitectsDaughter-Regular',
    marginVertical: 10,
    textAlign: 'center',
    color: '#2c6f33',
    fontStyle: 'italic',
  },
  // uncomment for rolling back to previous
  // soundButton: {
  //   position: 'absolute',
  //   top: 10,
  //   right: 10,
  //   // zIndex: 2,
  // },

  soundWrapper: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 5,
  },
  phoneticsBlob: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 6,
  },
  phoneticsText: {
    fontSize: 25,
    color: '#2c6f33',
  },
  soundButton: {
    borderRadius: 20,
    padding: 6,
    elevation: 3,
  },
  cardButtons: {
    position: 'absolute',
    bottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
  },
  exampleSection: {
    alignItems: 'flex-start',
    marginTop: 80,
    marginLeft: 30,
  },
  exampleBubble: {
    backgroundColor: '#cdf8b7ff',
    padding: 10,
    borderRadius: 12,
    marginTop: 8,
    borderColor: '#2c6f33',
    borderWidth: 1,
    maxWidth: '95%',
  },
  exampleText: {
    fontFamily: 'ArchitectsDaughter-Regular',
    fontStyle: 'italic',
    fontSize: 25,
    color: '#2c6f33',
  },
  bottomBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: 'space-evenly',
    alignItems: "center",
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  navText: {
    fontSize: 16,
    color: '#8feda0ff',
    fontFamily: 'ArchitectsDaughter-Regular',
    marginTop: 4,
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 14,
    color: '#2c6f33',
    fontFamily: 'ArchitectsDaughter-Regular',
    marginTop: -5,
    textAlign: 'center',
  },
});
