import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  initialsCircle: {
    backgroundColor: '#8feda0ff',
    borderColor: '#2c6f33',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1.5,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    color: '#2c6f33',
    fontWeight: 'bold',
    fontSize: 18,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#fff176',
    borderRadius: 20,
    width: 370,
    height: 300,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    position: 'relative',
  },
  word: {
    fontSize: 50,
    fontFamily: 'ArchitectsDaughter',
    fontWeight: 'bold',
    color: '#2c6f33',
  },
  definition: {
    fontSize: 30,
    fontFamily: 'ArchitectsDaughter',
    marginVertical: 10,
    textAlign: 'center',
    color: '#2c6f33',
    fontStyle: 'italic',
  },
  soundWrapper: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 5,
  },
  phoneticsUnder: {
    marginTop: 8,
    fontSize: 24,
    color: '#2c6f33',
    fontFamily: 'ArchitectsDaughter',
    textAlign: 'center',
  },
  soundButtonTopRight: {
    position: 'absolute',
    top: 10,
    right: 10,
    borderRadius: 20,
    padding: 6,
    zIndex: 5,
  },
  cardButtons: {
    position: 'absolute',
    bottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
  },
  exampleSection: {
    alignItems: 'flex-start',
    marginTop: 80,
    marginLeft: 30,
  },
  exampleBubble: {
    backgroundColor: '#cdf8b7ff',
    padding: 10,
    borderRadius: 12,
    marginTop: 8,
    borderColor: '#2c6f33',
    borderWidth: 1,
    maxWidth: '95%',
  },
  exampleText: {
    fontFamily: 'ArchitectsDaughter',
    fontStyle: 'italic',
    fontSize: 18,
    color: '#2c6f33',
  },
  bottomBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: 'space-evenly',
    alignItems: "center",
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  navText: {
    fontSize: 16,
    color: '#8feda0ff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 14,
    color: '#2c6f33',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },
  topicLabelInside: {
    position: 'absolute',
    top: 10,
    left: 10,
    fontFamily: 'ArchitectsDaughter',
    fontSize: 20,
    color: '#2c6f33',
    opacity: 0.88,
    fontWeight: 'bold',
    textShadowColor: '#c0e3bf',
    textShadowRadius: 2,
    letterSpacing: 0.2,
  },
  searchModalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.20)',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 105,
  },
  searchModalContainer: {
    backgroundColor: '#fae6ffff',
    padding: 24,
    borderRadius: 18,
    width: 340,
    shadowColor: '#333',
    shadowOpacity: 0.18,
    shadowOffset: { width: 2, height: 6 },
  },
  searchModalTitle: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 24,
    marginBottom: 8,
    color: '#2c6f33',
    textAlign: 'center',
  },
  searchInput: {
    borderColor: '#2c6f33',
    borderWidth: 1.5,
    borderRadius: 10,
    backgroundColor: '#fff',
    padding: 8,
    fontSize: 18,
    fontFamily: 'ArchitectsDaughter',
    marginBottom: 12,
  },
  noResultsText: {
    color: '#777',
    fontFamily: 'ArchitectsDaughter',
    marginBottom: 8,
    textAlign: 'center',
  },
  searchResultBox: {
    padding: 8,
    backgroundColor: '#eaffea',
    borderRadius: 7,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: '#b8efb7',
  },
  searchResultWord: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#2c6f33',
  },
  searchResultDef: {
    fontSize: 14,
    color: '#555',
    fontFamily: 'ArchitectsDaughter',
  },
  searchCloseBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
  searchCloseText: {
    color: '#767776ff',
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    fontWeight: 'bold',
  },
  hintText: {
    marginTop: 3,
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#2c6f33',
    marginLeft: 9,
  },
  navIconActive: {
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 4,
  },
  cardIconActive: {
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 8,

  },
  iconButton: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconButtonActive: {
    shadowColor: '#7704fbff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 4,
  },
});