import { StyleSheet, Dimensions } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  learnButton: {
    position: 'absolute',
    top: height * 0.015,
    right: width * 0.04,
    width: width * (2 / 3),
    height: height * (2.5 / 4),
    backgroundColor: '#b0fbb0e4',
    borderWidth: 1.5,
    borderColor: '#006400',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  learnText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#006400',
    fontFamily: 'ArchitectsDaughter',
  },
  progressButton: {
    position: 'absolute',
    top: height * 0.015,
    left: width * 0.05,
    width: width * 0.22,
    height: height * 0.09,
    backgroundColor: '#e2a4f7ee',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#006400',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  settingsButton: {
    position: 'absolute',
    bottom: 115,
    right: 20,
    backgroundColor: '#e2a4f7e2',
    width: width * 0.22,
    height: height * 0.09,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#006400',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  exitButton: {
    position: 'absolute',
    bottom: 13,
    right: 20,
    backgroundColor: '#eeff00fd',
    width: 90,
    height: 90,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#006400',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  buttonText: {
    fontSize: 19,
    fontFamily: 'ArchitectsDaughter',
    color: '#006400',
    textAlign: 'center',
  },
  smallButtonText: {
    fontSize: 16,
    fontFamily: 'ArchitectsDaughter',
    color: '#006400',
    textAlign: 'center',
  },
  bottomButtonsContainer: {
    position: 'absolute',
    bottom: 40,
    right: 30,
    alignItems: 'center',
  },
  constructorButton: {
    position: 'absolute',
    right: 121,
    bottom: 15,
    backgroundColor: '#e2a4f7e2',
    width: 160,
    height: 190,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#006400',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  walletButton: {
    position: 'absolute',
    bottom: 15,
    left: width * 0.05,
    width: width * 0.22, 
    height: 190, 
    backgroundColor: '#a1c1f5d6',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: '#006400',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  quizButton: {
    position: 'absolute',
    top: height * 0.12,
    left: width * 0.05,
    width: width * 0.22,
    height: height * 0.515,
    backgroundColor: '#e19bf8bf',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: '#006400',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 10,
    backgroundColor: '#E6E6FA',
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: 'ArchitectsDaughter-Bold',
    color: '#2c6f33ff',
  },
  userCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#87CEFA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  initials: {
    color: '#2c6f33ff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  initialsCircle: {
    backgroundColor: '#8feda0ff',
    borderColor: '#2c6f33',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1.5,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter-Regular',
    color: '#2c6f33',
    fontWeight: 'bold',
    fontSize: 18,
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 16,
    color: '#2c6f33',
    fontFamily: 'ArchitectsDaughter-Regular',
    marginTop: -2,
    textAlign: 'center',
  },
});

export default styles;
