import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  learnButton: {
    position: 'absolute',
    top: height * 0.015,
    right: width * 0.04,
    width: width * (2 / 3),
    height: height * (2.5 / 4),
    backgroundColor: '#97fa97b0',
    borderWidth: 1.5,
    borderColor: '#00640064',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
    shadowRadius: 3,
  },
  learnText: {
    fontSize: 50,
    fontWeight: 'bold',
    color: '#006400',
    fontFamily: 'ArchitectsDaughter',
  },
  learnButtonActive: {
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 12, // крупная кнопка — чуть шире свечение
  },
  progressButton: {
    position: 'absolute',
    top: height * 0.015,
    left: width * 0.05,
    width: width * 0.22,
    height: height * 0.09,
    backgroundColor: '#e3a4f8c7',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#00640064',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  progressButtonActive: {
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 8,
  },
  progressIcon: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  quizButton: {
    position: 'absolute',
    top: height * 0.12,
    left: width * 0.05,
    width: width * 0.22,
    height: height * 0.515,
    backgroundColor: '#e3a4f8c7',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: '#00640064',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  quizButtonActive: {
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 12,
  },
  quizIcon: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  walletButton: {
    position: 'absolute',
    bottom: 15,
    left: width * 0.05,
    width: width * 0.22,
    height: 190,
    backgroundColor: '#a0c1f8c0',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: '#00640064',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  walletButtonActive: {
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  walletIcon: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  constructorButton: {
    position: 'absolute',
    right: 121,
    bottom: 15,
    backgroundColor: '#e3a4f8c7',
    width: 160,
    height: 190,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#00640064',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  constructorButtonActive: {
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  settingsButton: {
    position: 'absolute',
    bottom: 120,
    right: 20,
    backgroundColor: '#e3a4f8c7',
    width: width * 0.22,
    height: height * 0.09,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#00640064',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  settingsButtonActive: {
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 8,
  },
  settingsIcon: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  exitButton: {
    position: 'absolute',
    bottom: 16,
    right: 20,
    backgroundColor: '#ecf83eda',
    width: 90,
    height: 90,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#00640064',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  exitButtonActive: {
    borderColor: '#ffffff',
    shadowColor: '#ffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  exitIcon: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
// Texts on buttons
  buttonText: {
    fontSize: 20,
    fontFamily: 'ArchitectsDaughter',
    color: '#006400',
    textAlign: 'center',
    marginBottom: -7
  },
  smallButtonText: {
    fontSize: 14,
    fontFamily: 'ArchitectsDaughter',
    color: '#006400',
    textAlign: 'center',
    marginBottom: -7,
  },
  bottomButtonsContainer: {
    position: 'absolute',
    bottom: 40,
    right: 30,
    alignItems: 'center',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 10,
    backgroundColor: '#E6E6FA',
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: 'ArchitectsDaughter',
    color: '#2c6f33ff',
  },
  userCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#87CEFA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  initials: {
    color: '#2c6f33ff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  initialsCircle: {
    backgroundColor: '#8feda0ff',
    borderColor: '#00640064',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1.5,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    color: '#2c6f33',
    fontWeight: 'bold',
    fontSize: 18,
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 14,
    color: '#2c6f33',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },


});

export default styles;
