import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 20,
    paddingHorizontal: 10,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  initialsCircle: {
    backgroundColor: '#87CEFA',
    borderColor: '#669dcaff',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1.5,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    color: '#246396',
    fontWeight: 'bold',
    fontSize: 18,
  },
  buttonGroup: {
    marginTop: 20,
    width: '100%',
    alignItems: 'center',
  },
  metricButton: {
    width: '85%',
    backgroundColor: '#87CEFA',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#669dcaff',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 2, height: 2 },
  },
  metricText: {
    fontSize: 20,
    fontFamily: 'ArchitectsDaughter',
    color: '#246396ff',
  },
  homeButton: {
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 14,
    fontFamily: 'ArchitectsDaughter',
    color: '#246396ff',
    marginTop: 4,
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 5,
    paddingTop: 5,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 14,
    color: '#077bb4ff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },
  navText: {
    fontSize: 14,
    color: '#97d0feff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
    textAlign: 'center',
    width: '100%',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    marginHorizontal: 10,
  },
  buttonBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#246396ff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 3,
    backgroundColor: '#87CEFA',
  },
  navIconActive: {
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 4,
  },
});

export default styles;
