import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 4, height: 6 },
  },
  initialsCircle: {
    backgroundColor: '#97d0feff',
    borderRadius: 20,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: "#246396",
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#246396',
    fontWeight: 'bold'
  },
  questionButton: {
    backgroundColor: '#fff176',
    borderRadius: 30,
    padding: 15,
    marginBottom: 20,
    marginTop: 10,
    minHeight: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#777777',
    shadowOpacity: 0.35,
    shadowOffset: { width: 5, height: 6 },
    elevation: 2,
  },
  questionText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 40,
    color: '#2c6f33',
    textAlign: 'center',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  answersContainer: {
    gap: 15,
    paddingBottom: 100,
  },
  answerBox: {
    backgroundColor: '#f9dafafd',
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: '#97d0feff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  selectedAnswerBox: {
    backgroundColor: '#97d0feff',
    borderColor: '#246396',
    borderWidth: 2,
  },
  correctAnswerBox: {
    backgroundColor: '#cbf6b6ff',
    borderColor: '#2c6f33',
  },
  wrongAnswerBox: {
    backgroundColor: '#f86a6aff',
    borderColor: '#c62828',
  },
  answerText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 25,
    color: '#2c6f33',
    textAlign: 'center',
  },
  bottomBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 4, height: 6 },
  },
  navigationButton: {
    backgroundColor: 'transparent',
    padding: 10,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  navText: {
    fontSize: 14,
    color: '#97d0feff',
    fontFamily: 'ArchitectsDaughter-Regular',
    marginTop: 4,
    textAlign: 'center',
    width: '100%', 
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 16,
    color: '#246396',
    fontFamily: 'ArchitectsDaughter-Regular',
    marginTop: -2,
    textAlign: 'center',
  },
});

export default styles;
