import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  content: {
    flex: 1,
    paddingTop: 10,
    paddingBottom: 110,
  },
  label: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 20,
    color: '#246396',
    marginBottom: 1,
    marginTop: 1,
  },
  inputBase: {
    width: '100%',
    borderWidth: 3,
    borderColor: '#bf86fca8',
    borderRadius: 20,
    backgroundColor: '#fbf6fbfd',
    marginBottom: 16,
    shadowColor: '#313131ff',
    shadowOpacity: 0.5,
    shadowOffset: { width: 3, height: 6 },
    shadowRadius: 2,
  },
  inputFocused: {
    borderColor: '#ffffff',
    borderWidth: 2,
    borderRadius: 20,
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  inputField: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    fontSize: 18,
    fontFamily: 'ArchitectsDaughter',
    color: '#246396',
    backgroundColor: 'transparent',
  },
  disabledInput: {
    backgroundColor: '#f4f4f4',
    color: '#4d4e4dff',
  },
  deleteWrapper: {
    alignItems: 'center',
    marginTop: 28,
    marginBottom: 20,
  },
  pillButton: {
    backgroundColor: '#97d0fea8',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 30,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#97d0fefe',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
    shadowRadius: 6,
  },
  pillButtonActive: {
    borderColor: '#ffffffff',
    borderWidth: 2,
    shadowColor: '#ffffffff',
    shadowOpacity: 0.9,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  pillButtonText: {
    color: '#246396',
    fontSize: 20,
    textAlign: 'center',
    fontFamily: 'ArchitectsDaughter',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navText: {
    fontSize: 14,
    color: '#97d0feff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
    textAlign: 'center',
    width: '100%',
  },
  navIconActive: {
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 4,
  },
  initialsCircle: {
    backgroundColor: '#97d0feff',
    borderRadius: 20,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#246396',
    top: -2,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#246396',
    fontWeight: 'bold',
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 5,
    paddingTop: 5,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 14,
    color: '#246396',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },
});

export default styles;
