import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  label: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 20,
    color: '#246396',
    marginBottom: 1,
    marginTop: 1,

  },
  input: {
    borderWidth: 3,
    borderColor: '#acb5fbf3',
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 18,
    fontSize: 18,
    backgroundColor: '#fbf6fbfd',
    color: '#738275ff',
    fontFamily: 'ArchitectsDaughter',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  disabledInput: {
    backgroundColor: '#f4f4f4',
    color: '#888',
  },
  saveButton: {
    backgroundColor: 'transparent',
    padding: 10,
    borderRadius: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  saveButtonText: {
    fontSize: 16,
    color: '#97d0feff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
    textAlign: 'center',
  },
  // deleteButton: {
  //   marginTop: 38,
  //   padding: 14,
  //   borderRadius: 30,
  //   alignItems: 'center',
  //   backgroundColor: '#fff0f0',
  //   borderWidth: 1.5,
  //   borderColor: '#ee3d3d',
  //   shadowColor: '#000',
  //   shadowOpacity: 0.15,
  //   shadowRadius: 2,
  //   elevation: 2,
  // },
  // deleteButtonText: {
  //   color: '#ee3d3d',
  //   fontFamily: 'ArchitectsDaughter',
  //   fontSize: 18,
  //   fontWeight: 'bold',
  // },
  bottomBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navText: {
    fontSize: 14,
    color: '#97d0feff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
    textAlign: 'center',
    width: '100%',
  },
  navigationButton: {
    // backgroundColor: 'transparent',
    padding: 10,
    borderRadius: 30,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  initialsCircle: {
    backgroundColor: '#97d0feff',
    borderRadius: 20,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: "#246396",
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#246396',
    fontWeight: 'bold'
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 5,
    paddingTop: 5,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 14,
    color: '#246396',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },

  deleteWrapper: {
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 30,
  },

  deleteAccountButton: {
    backgroundColor: '#97d0feff',        
    paddingVertical: 12,
    paddingHorizontal: 36,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#246396',              
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },

  deleteAccountText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#246396',                    
    fontFamily: 'ArchitectsDaughter',
    textAlign: 'center',
  },
navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
});

export default styles;
