import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 50,
  },
  title: {
    fontSize: 45,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'ArchitectsDaughter',
    color: '#b869d3ff',
    textShadowColor: '#313131ff',
    textShadowOffset: { width: 3, height: 6 },
    textShadowRadius: 6,
    shadowOpacity: 0.1,
  },
  avatar: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
  },
  avatarWrapper: {
    borderRadius: 20,
    padding: 4,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
    shadowRadius: 1,
  },
  inputBase: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#00640064',
    borderRadius: 20,
    backgroundColor: '#ebf8e4ff',
    marginBottom: 15,
    shadowColor: '#313131ff',
    shadowOpacity: 0.5,
    shadowOffset: { width: 3, height: 6 },
    shadowRadius: 2,
  },
  inputFocused: {
    borderColor: '#ffffff',
    borderWidth: 2,
    borderRadius: 18,
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  inputField: {
    padding: 12,
    fontSize: 20,
    fontFamily: 'ArchitectsDaughter',
    backgroundColor: 'transparent',
    color: '#006400'
  },
  forgotText: {
    color: '#006400',
    textDecorationLine: 'underline',
    marginTop: 30,
    fontSize: 16,
    fontFamily: 'ArchitectsDaughter',
  },
  pillButton: {
    backgroundColor: '#d97cf885',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 30,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#00640064',
    marginTop: 30,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
    shadowRadius: 6,
  },
  pillButtonActive: {
    borderColor: '#ffffffff',
    shadowColor: '#ffffffff',
    borderWidth: 2,
    shadowOpacity: 0.8,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  pillButtonText: {
    color: '#006400',
    fontSize: 20,
    textAlign: 'center',
    fontFamily: 'ArchitectsDaughter',
  },
});

export default styles;
