import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20 },
  topicList: {
    paddingTop: 20,
    paddingBottom: 20,
  },
  topicBoxWrapper: {
    marginVertical: 10,
    alignItems: 'center',
    shadowColor: '#313131FF',
    shadowOpacity: 0.8,
    shadowOffset: { width: 4, height: 6 },
    shadowRadius: 6,
  },
  pillButton: {
    width: 300,
    height: 70,
    borderRadius: 30,
    paddingVertical: 20,
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2, // как в Quiz
    alignSelf: 'center',
  },
  pillButtonActiveBorder: {
    borderColor: '#FFFFFF',
    borderWidth: 2,
  },
  pillButtonWhiteShadow: {
    marginVertical: 10,
    alignItems: 'center',
    shadowColor: '#FFFFFF',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 9,
    borderRadius: 40,
  },
  topicText: {
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'ArchitectsDaughter',
    color: '#006400',
  },
  topicTextActive: {
    color: '#b67ef6ff',
    textShadowColor: '#006400',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 2,
  },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  initialsCircle: {
    backgroundColor: '#b8efb7',
    borderRadius: 20,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#2c6f33',
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#2c6f33',
    fontWeight: 'bold',
  },
  userLabel: {
    fontSize: 14,
    color: '#2c6f33',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#313131FF',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navText: {
    fontSize: 14,
    color: '#8feda0ff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
    width: '100%',
  },
  navIconCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconActive: {
    shadowColor: '#FFFFFF',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 4,
  },
  searchModalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.20)',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 105,
  },
  searchModalContainer: {
    backgroundColor: '#fae6ffff',
    padding: 24,
    borderRadius: 18,
    width: 340,
    maxHeight: '80%',
    shadowColor: '#333',
    shadowOpacity: 0.18,
    shadowOffset: { width: 2, height: 6 },
  },
  searchModalTitle: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 24,
    marginBottom: 8,
    color: '#2c6f33',
    textAlign: 'center',
  },
  searchInput: {
    borderColor: '#2c6f33',
    borderWidth: 1.5,
    borderRadius: 10,
    backgroundColor: '#fff',
    padding: 8,
    fontSize: 18,
    fontFamily: 'ArchitectsDaughter',
    marginBottom: 12,
  },
  noResultsText: {
    color: '#777',
    fontFamily: 'ArchitectsDaughter',
    marginBottom: 8,
    textAlign: 'center',
  },
  searchResultBox: {
    padding: 8,
    backgroundColor: '#eaffea',
    borderRadius: 7,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: '#b8efb7',
  },
  searchResultWord: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#2c6f33',
  },
  searchResultDef: {
    fontSize: 14,
    color: '#555',
    fontFamily: 'ArchitectsDaughter',
  },
  searchCloseBtn: { position: 'absolute', top: 6, right: 6 },
});

export default styles;
