import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
  },
  topicList: {
    paddingBottom: 20,
  },
  topicBoxWrapper: {
    marginVertical: 10,
    alignItems: 'center',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  topicTouchable: {
    borderRadius: 40,
    overflow: 'visible',
  },
  topicBox: {
    width: 300,
    height: 80,
    borderRadius: 40,
    paddingVertical: 20,
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    elevation: 0,
  },
  topicText: {
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'ArchitectsDaughter-Regular',
    color: '#006400',
  },
  topicTextActive: {
    color: '#b67ef6ff',
    textShadowColor: '#006400',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 2,
  },
  topicShadowWrapper: {
    shadowColor: '#006400',
    shadowOffset: { width: 1, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    borderRadius: 20,
    backgroundColor: 'transparent',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  simpleButton: {
    backgroundColor: '#F8C8DC',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#006400',
    marginTop: 30,
  },
  simpleButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#006400',
    fontFamily: 'ArchitectsDaughter',
  },
  initialsCircle: {
    backgroundColor: '#8feda0ff',
    borderColor: '#2c6f33',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderRadius: 20,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter-Regular',
    color: '#2c6f33',
    fontWeight: 'bold',
    fontSize: 18,
  },
  bottomBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 4, height: 6 },
  },
  homeButton: {
    alignItems: 'center',
  },
  addButton: {
    width: 56,
    height: 56,
    backgroundColor: '#9edd81ff',
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  buttonText: {
    color: '#006400',
    marginTop: 4,
    fontFamily: 'ArchitectsDaughter',
    fontSize: 14,
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 8,
    paddingTop: 8,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 16,
    color: '#2c6f33',
    fontFamily: 'ArchitectsDaughter-Regular',
    marginTop: -2,
    textAlign: 'center',
  },
  navText: {
    fontSize: 16,
    fontFamily: 'ArchitectsDaughter',
    color: '#8feda0ff',
    textAlign: 'center',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    marginHorizontal: 10
  },
});

export default styles;
