import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  searchBar: {
    backgroundColor: "#ffffffdd",
    fontFamily: 'ArchitectsDaughter',
    borderRadius: 30,
    padding: 10,
    marginBottom: 30,
    fontSize: 18,
    color: '#767677ff',
    borderWidth: 3,
    borderColor: "#313bae8c",
    gap: 12,
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  cardList: {
    gap: 12,
    paddingBottom: 80,
  },
  cardRow: {
    backgroundColor: "#faef8dff",
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    justifyContent: "space-between",
    borderWidth: 2,
    borderColor: "#f8f4c5ff",
    gap: 12,
    width: '99%',
    overflow: 'visible',
  },
  initials: {
    color: '#2c6f33ff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  initialsCircle: {
    backgroundColor: '#97d0feff',
    borderColor: '#313bae8c',
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1.5,
  },
  initialsText: {
    fontFamily: 'ArchitectsDaughter',
    color: "#246396",
    fontWeight: 'bold',
    fontSize: 18,
  },
  termText: {
    fontFamily: 'ArchitectsDaughter',
    fontSize: 18,
    color: '#246396',
    fontWeight: 'normal',
  },
  bottomBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navText: {
    fontSize: 14,
    color: '#93cbf9ff',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
    textAlign: 'center',
    width: '100%',
  },
  userWrapper: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginRight: 5,
    paddingTop: 5,
    minWidth: 60,
  },
  userLabel: {
    fontSize: 14,
    color: '#313bae8c',
    fontFamily: 'ArchitectsDaughter',
    marginTop: -5,
    textAlign: 'center',
  },
  iconRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    overflow: 'visible',
    zIndex: 1,
  },
  returnCircleWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  returnCircle: {
    width: 25,
    height: 25,
    borderRadius: 18,
    backgroundColor: '#93cbf9ff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 3, height: 6 },
  },
  returnLabel: {
    fontSize: 12,
    color: '#246396',
    fontFamily: 'ArchitectsDaughter',
    marginTop: 4,
    textAlign: 'center',
  },
  inputBase: {
    width: '100%',
    borderWidth: 3,
    borderColor: '#313bae61',
    borderRadius: 20,
    backgroundColor: '#e3f8f2fc',
    marginBottom: 16,
    shadowColor: '#313131ff',
    shadowOpacity: 0.5,
    shadowOffset: { width: 3, height: 6 },
    shadowRadius: 2,
  },
  inputFocused: {
    borderColor: '#ffffff',
    borderWidth: 2,
    borderRadius: 20,
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  inputField: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    fontSize: 18,
    fontFamily: 'ArchitectsDaughter',
    color: '#4d4e4dff',
    backgroundColor: 'transparent',
  },
  disabledInput: {
    backgroundColor: '#f4f4f4',
    color: '#4d4e4dff',
  },
  navIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#246396ff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#313131ff',
    shadowOpacity: 0.8,
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 3,
    backgroundColor: '#87CEFA',
  },
  navIconActive: {
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 4,
  },
  iconButton: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconButtonActive: {
    shadowColor: '#ffffffff',
    shadowOpacity: 1,
    shadowOffset: { width: 1, height: 1 },
    shadowRadius: 4,
    borderRadius: 18,
  },
  iconGlyphGlow: {
    textShadowColor: '#ffffff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
});

export default styles;
